/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as SettingsWorkspaceRouteImport } from './routes/settings.workspace'
import { Route as SettingsSandboxesRouteImport } from './routes/settings.sandboxes'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsMembersRouteImport } from './routes/settings.members'
import { Route as ProjectProjectIdRouteImport } from './routes/project.$projectId'
import { Route as OnboardingWorkspaceRouteImport } from './routes/onboarding/workspace'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding/welcome'
import { Route as OnboardingThemeRouteImport } from './routes/onboarding/theme'
import { Route as OnboardingProjectRouteImport } from './routes/onboarding/project'
import { Route as OnboardingInviteRouteImport } from './routes/onboarding/invite'
import { Route as OnboardingDoneRouteImport } from './routes/onboarding/done'
import { Route as ProjectProjectIdIndexRouteImport } from './routes/project.$projectId.index'
import { Route as ProjectProjectIdWorkflowsRouteImport } from './routes/project.$projectId.workflows'
import { Route as ProjectProjectIdUsageRouteImport } from './routes/project.$projectId.usage'
import { Route as ProjectProjectIdSettingsRouteImport } from './routes/project.$projectId.settings'
import { Route as ProjectProjectIdSessionsRouteImport } from './routes/project.$projectId.sessions'
import { Route as ProjectProjectIdRoadmapsRouteImport } from './routes/project.$projectId.roadmaps'
import { Route as ProjectProjectIdRoadmapRouteImport } from './routes/project.$projectId.roadmap'
import { Route as ProjectProjectIdRecoveryRouteImport } from './routes/project.$projectId.recovery'
import { Route as ProjectProjectIdMetricsRouteImport } from './routes/project.$projectId.metrics'
import { Route as ProjectProjectIdInsightsRouteImport } from './routes/project.$projectId.insights'
import { Route as ProjectProjectIdGatesRouteImport } from './routes/project.$projectId.gates'
import { Route as ProjectProjectIdFeaturesRouteImport } from './routes/project.$projectId.features'
import { Route as ProjectProjectIdEventsRouteImport } from './routes/project.$projectId.events'
import { Route as ProjectProjectIdEpicsRouteImport } from './routes/project.$projectId.epics'
import { Route as ProjectProjectIdConfigRouteImport } from './routes/project.$projectId.config'
import { Route as ProjectProjectIdChainsRouteImport } from './routes/project.$projectId.chains'
import { Route as ProjectProjectIdArtifactsRouteImport } from './routes/project.$projectId.artifacts'
import { Route as ProjectProjectIdAgentsRouteImport } from './routes/project.$projectId.agents'
import { Route as ProjectProjectIdSettingsIndexRouteImport } from './routes/project.$projectId.settings.index'
import { Route as ProjectProjectIdSessionsIndexRouteImport } from './routes/project.$projectId.sessions.index'
import { Route as ProjectProjectIdFeaturesIndexRouteImport } from './routes/project.$projectId.features.index'
import { Route as ProjectProjectIdArtifactsIndexRouteImport } from './routes/project.$projectId.artifacts.index'
import { Route as ProjectProjectIdSettingsGithubRouteImport } from './routes/project.$projectId.settings.github'
import { Route as ProjectProjectIdSettingsGeneralRouteImport } from './routes/project.$projectId.settings.general'
import { Route as ProjectProjectIdSettingsEnvironmentRouteImport } from './routes/project.$projectId.settings.environment'
import { Route as ProjectProjectIdSettingsDnsRouteImport } from './routes/project.$projectId.settings.dns'
import { Route as ProjectProjectIdSessionsSessionIdRouteImport } from './routes/project.$projectId.sessions.$sessionId'
import { Route as ProjectProjectIdFeaturesFeatureIdRouteImport } from './routes/project.$projectId.features.$featureId'
import { Route as ProjectProjectIdEpicsEpicIdRouteImport } from './routes/project.$projectId.epics.$epicId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const SettingsWorkspaceRoute = SettingsWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSandboxesRoute = SettingsSandboxesRouteImport.update({
  id: '/sandboxes',
  path: '/sandboxes',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMembersRoute = SettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingWorkspaceRoute = OnboardingWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingThemeRoute = OnboardingThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingProjectRoute = OnboardingProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingInviteRoute = OnboardingInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingDoneRoute = OnboardingDoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => OnboardingRoute,
} as any)
const ProjectProjectIdIndexRoute = ProjectProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdWorkflowsRoute =
  ProjectProjectIdWorkflowsRouteImport.update({
    id: '/workflows',
    path: '/workflows',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdUsageRoute = ProjectProjectIdUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdSettingsRoute =
  ProjectProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdSessionsRoute =
  ProjectProjectIdSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdRoadmapsRoute =
  ProjectProjectIdRoadmapsRouteImport.update({
    id: '/roadmaps',
    path: '/roadmaps',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdRoadmapRoute = ProjectProjectIdRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdRecoveryRoute =
  ProjectProjectIdRecoveryRouteImport.update({
    id: '/recovery',
    path: '/recovery',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdMetricsRoute = ProjectProjectIdMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdInsightsRoute =
  ProjectProjectIdInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdGatesRoute = ProjectProjectIdGatesRouteImport.update({
  id: '/gates',
  path: '/gates',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdFeaturesRoute =
  ProjectProjectIdFeaturesRouteImport.update({
    id: '/features',
    path: '/features',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdEventsRoute = ProjectProjectIdEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdEpicsRoute = ProjectProjectIdEpicsRouteImport.update({
  id: '/epics',
  path: '/epics',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdConfigRoute = ProjectProjectIdConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdChainsRoute = ProjectProjectIdChainsRouteImport.update({
  id: '/chains',
  path: '/chains',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdArtifactsRoute =
  ProjectProjectIdArtifactsRouteImport.update({
    id: '/artifacts',
    path: '/artifacts',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdAgentsRoute = ProjectProjectIdAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdSettingsIndexRoute =
  ProjectProjectIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectProjectIdSettingsRoute,
  } as any)
const ProjectProjectIdSessionsIndexRoute =
  ProjectProjectIdSessionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectProjectIdSessionsRoute,
  } as any)
const ProjectProjectIdFeaturesIndexRoute =
  ProjectProjectIdFeaturesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectProjectIdFeaturesRoute,
  } as any)
const ProjectProjectIdArtifactsIndexRoute =
  ProjectProjectIdArtifactsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectProjectIdArtifactsRoute,
  } as any)
const ProjectProjectIdSettingsGithubRoute =
  ProjectProjectIdSettingsGithubRouteImport.update({
    id: '/github',
    path: '/github',
    getParentRoute: () => ProjectProjectIdSettingsRoute,
  } as any)
const ProjectProjectIdSettingsGeneralRoute =
  ProjectProjectIdSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => ProjectProjectIdSettingsRoute,
  } as any)
const ProjectProjectIdSettingsEnvironmentRoute =
  ProjectProjectIdSettingsEnvironmentRouteImport.update({
    id: '/environment',
    path: '/environment',
    getParentRoute: () => ProjectProjectIdSettingsRoute,
  } as any)
const ProjectProjectIdSettingsDnsRoute =
  ProjectProjectIdSettingsDnsRouteImport.update({
    id: '/dns',
    path: '/dns',
    getParentRoute: () => ProjectProjectIdSettingsRoute,
  } as any)
const ProjectProjectIdSessionsSessionIdRoute =
  ProjectProjectIdSessionsSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => ProjectProjectIdSessionsRoute,
  } as any)
const ProjectProjectIdFeaturesFeatureIdRoute =
  ProjectProjectIdFeaturesFeatureIdRouteImport.update({
    id: '/$featureId',
    path: '/$featureId',
    getParentRoute: () => ProjectProjectIdFeaturesRoute,
  } as any)
const ProjectProjectIdEpicsEpicIdRoute =
  ProjectProjectIdEpicsEpicIdRouteImport.update({
    id: '/$epicId',
    path: '/$epicId',
    getParentRoute: () => ProjectProjectIdEpicsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/onboarding/done': typeof OnboardingDoneRoute
  '/onboarding/invite': typeof OnboardingInviteRoute
  '/onboarding/project': typeof OnboardingProjectRoute
  '/onboarding/theme': typeof OnboardingThemeRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/settings/members': typeof SettingsMembersRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/sandboxes': typeof SettingsSandboxesRoute
  '/settings/workspace': typeof SettingsWorkspaceRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/project/$projectId/agents': typeof ProjectProjectIdAgentsRoute
  '/project/$projectId/artifacts': typeof ProjectProjectIdArtifactsRouteWithChildren
  '/project/$projectId/chains': typeof ProjectProjectIdChainsRoute
  '/project/$projectId/config': typeof ProjectProjectIdConfigRoute
  '/project/$projectId/epics': typeof ProjectProjectIdEpicsRouteWithChildren
  '/project/$projectId/events': typeof ProjectProjectIdEventsRoute
  '/project/$projectId/features': typeof ProjectProjectIdFeaturesRouteWithChildren
  '/project/$projectId/gates': typeof ProjectProjectIdGatesRoute
  '/project/$projectId/insights': typeof ProjectProjectIdInsightsRoute
  '/project/$projectId/metrics': typeof ProjectProjectIdMetricsRoute
  '/project/$projectId/recovery': typeof ProjectProjectIdRecoveryRoute
  '/project/$projectId/roadmap': typeof ProjectProjectIdRoadmapRoute
  '/project/$projectId/roadmaps': typeof ProjectProjectIdRoadmapsRoute
  '/project/$projectId/sessions': typeof ProjectProjectIdSessionsRouteWithChildren
  '/project/$projectId/settings': typeof ProjectProjectIdSettingsRouteWithChildren
  '/project/$projectId/usage': typeof ProjectProjectIdUsageRoute
  '/project/$projectId/workflows': typeof ProjectProjectIdWorkflowsRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/epics/$epicId': typeof ProjectProjectIdEpicsEpicIdRoute
  '/project/$projectId/features/$featureId': typeof ProjectProjectIdFeaturesFeatureIdRoute
  '/project/$projectId/sessions/$sessionId': typeof ProjectProjectIdSessionsSessionIdRoute
  '/project/$projectId/settings/dns': typeof ProjectProjectIdSettingsDnsRoute
  '/project/$projectId/settings/environment': typeof ProjectProjectIdSettingsEnvironmentRoute
  '/project/$projectId/settings/general': typeof ProjectProjectIdSettingsGeneralRoute
  '/project/$projectId/settings/github': typeof ProjectProjectIdSettingsGithubRoute
  '/project/$projectId/artifacts/': typeof ProjectProjectIdArtifactsIndexRoute
  '/project/$projectId/features/': typeof ProjectProjectIdFeaturesIndexRoute
  '/project/$projectId/sessions/': typeof ProjectProjectIdSessionsIndexRoute
  '/project/$projectId/settings/': typeof ProjectProjectIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/onboarding/done': typeof OnboardingDoneRoute
  '/onboarding/invite': typeof OnboardingInviteRoute
  '/onboarding/project': typeof OnboardingProjectRoute
  '/onboarding/theme': typeof OnboardingThemeRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/settings/members': typeof SettingsMembersRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/sandboxes': typeof SettingsSandboxesRoute
  '/settings/workspace': typeof SettingsWorkspaceRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/project/$projectId/agents': typeof ProjectProjectIdAgentsRoute
  '/project/$projectId/chains': typeof ProjectProjectIdChainsRoute
  '/project/$projectId/config': typeof ProjectProjectIdConfigRoute
  '/project/$projectId/epics': typeof ProjectProjectIdEpicsRouteWithChildren
  '/project/$projectId/events': typeof ProjectProjectIdEventsRoute
  '/project/$projectId/gates': typeof ProjectProjectIdGatesRoute
  '/project/$projectId/insights': typeof ProjectProjectIdInsightsRoute
  '/project/$projectId/metrics': typeof ProjectProjectIdMetricsRoute
  '/project/$projectId/recovery': typeof ProjectProjectIdRecoveryRoute
  '/project/$projectId/roadmap': typeof ProjectProjectIdRoadmapRoute
  '/project/$projectId/roadmaps': typeof ProjectProjectIdRoadmapsRoute
  '/project/$projectId/usage': typeof ProjectProjectIdUsageRoute
  '/project/$projectId/workflows': typeof ProjectProjectIdWorkflowsRoute
  '/project/$projectId': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/epics/$epicId': typeof ProjectProjectIdEpicsEpicIdRoute
  '/project/$projectId/features/$featureId': typeof ProjectProjectIdFeaturesFeatureIdRoute
  '/project/$projectId/sessions/$sessionId': typeof ProjectProjectIdSessionsSessionIdRoute
  '/project/$projectId/settings/dns': typeof ProjectProjectIdSettingsDnsRoute
  '/project/$projectId/settings/environment': typeof ProjectProjectIdSettingsEnvironmentRoute
  '/project/$projectId/settings/general': typeof ProjectProjectIdSettingsGeneralRoute
  '/project/$projectId/settings/github': typeof ProjectProjectIdSettingsGithubRoute
  '/project/$projectId/artifacts': typeof ProjectProjectIdArtifactsIndexRoute
  '/project/$projectId/features': typeof ProjectProjectIdFeaturesIndexRoute
  '/project/$projectId/sessions': typeof ProjectProjectIdSessionsIndexRoute
  '/project/$projectId/settings': typeof ProjectProjectIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/onboarding/done': typeof OnboardingDoneRoute
  '/onboarding/invite': typeof OnboardingInviteRoute
  '/onboarding/project': typeof OnboardingProjectRoute
  '/onboarding/theme': typeof OnboardingThemeRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/settings/members': typeof SettingsMembersRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/sandboxes': typeof SettingsSandboxesRoute
  '/settings/workspace': typeof SettingsWorkspaceRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/project/$projectId/agents': typeof ProjectProjectIdAgentsRoute
  '/project/$projectId/artifacts': typeof ProjectProjectIdArtifactsRouteWithChildren
  '/project/$projectId/chains': typeof ProjectProjectIdChainsRoute
  '/project/$projectId/config': typeof ProjectProjectIdConfigRoute
  '/project/$projectId/epics': typeof ProjectProjectIdEpicsRouteWithChildren
  '/project/$projectId/events': typeof ProjectProjectIdEventsRoute
  '/project/$projectId/features': typeof ProjectProjectIdFeaturesRouteWithChildren
  '/project/$projectId/gates': typeof ProjectProjectIdGatesRoute
  '/project/$projectId/insights': typeof ProjectProjectIdInsightsRoute
  '/project/$projectId/metrics': typeof ProjectProjectIdMetricsRoute
  '/project/$projectId/recovery': typeof ProjectProjectIdRecoveryRoute
  '/project/$projectId/roadmap': typeof ProjectProjectIdRoadmapRoute
  '/project/$projectId/roadmaps': typeof ProjectProjectIdRoadmapsRoute
  '/project/$projectId/sessions': typeof ProjectProjectIdSessionsRouteWithChildren
  '/project/$projectId/settings': typeof ProjectProjectIdSettingsRouteWithChildren
  '/project/$projectId/usage': typeof ProjectProjectIdUsageRoute
  '/project/$projectId/workflows': typeof ProjectProjectIdWorkflowsRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/epics/$epicId': typeof ProjectProjectIdEpicsEpicIdRoute
  '/project/$projectId/features/$featureId': typeof ProjectProjectIdFeaturesFeatureIdRoute
  '/project/$projectId/sessions/$sessionId': typeof ProjectProjectIdSessionsSessionIdRoute
  '/project/$projectId/settings/dns': typeof ProjectProjectIdSettingsDnsRoute
  '/project/$projectId/settings/environment': typeof ProjectProjectIdSettingsEnvironmentRoute
  '/project/$projectId/settings/general': typeof ProjectProjectIdSettingsGeneralRoute
  '/project/$projectId/settings/github': typeof ProjectProjectIdSettingsGithubRoute
  '/project/$projectId/artifacts/': typeof ProjectProjectIdArtifactsIndexRoute
  '/project/$projectId/features/': typeof ProjectProjectIdFeaturesIndexRoute
  '/project/$projectId/sessions/': typeof ProjectProjectIdSessionsIndexRoute
  '/project/$projectId/settings/': typeof ProjectProjectIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/login'
    | '/onboarding'
    | '/settings'
    | '/signup'
    | '/onboarding/done'
    | '/onboarding/invite'
    | '/onboarding/project'
    | '/onboarding/theme'
    | '/onboarding/welcome'
    | '/onboarding/workspace'
    | '/project/$projectId'
    | '/settings/members'
    | '/settings/profile'
    | '/settings/sandboxes'
    | '/settings/workspace'
    | '/onboarding/'
    | '/settings/'
    | '/project/$projectId/agents'
    | '/project/$projectId/artifacts'
    | '/project/$projectId/chains'
    | '/project/$projectId/config'
    | '/project/$projectId/epics'
    | '/project/$projectId/events'
    | '/project/$projectId/features'
    | '/project/$projectId/gates'
    | '/project/$projectId/insights'
    | '/project/$projectId/metrics'
    | '/project/$projectId/recovery'
    | '/project/$projectId/roadmap'
    | '/project/$projectId/roadmaps'
    | '/project/$projectId/sessions'
    | '/project/$projectId/settings'
    | '/project/$projectId/usage'
    | '/project/$projectId/workflows'
    | '/project/$projectId/'
    | '/project/$projectId/epics/$epicId'
    | '/project/$projectId/features/$featureId'
    | '/project/$projectId/sessions/$sessionId'
    | '/project/$projectId/settings/dns'
    | '/project/$projectId/settings/environment'
    | '/project/$projectId/settings/general'
    | '/project/$projectId/settings/github'
    | '/project/$projectId/artifacts/'
    | '/project/$projectId/features/'
    | '/project/$projectId/sessions/'
    | '/project/$projectId/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/login'
    | '/signup'
    | '/onboarding/done'
    | '/onboarding/invite'
    | '/onboarding/project'
    | '/onboarding/theme'
    | '/onboarding/welcome'
    | '/onboarding/workspace'
    | '/settings/members'
    | '/settings/profile'
    | '/settings/sandboxes'
    | '/settings/workspace'
    | '/onboarding'
    | '/settings'
    | '/project/$projectId/agents'
    | '/project/$projectId/chains'
    | '/project/$projectId/config'
    | '/project/$projectId/epics'
    | '/project/$projectId/events'
    | '/project/$projectId/gates'
    | '/project/$projectId/insights'
    | '/project/$projectId/metrics'
    | '/project/$projectId/recovery'
    | '/project/$projectId/roadmap'
    | '/project/$projectId/roadmaps'
    | '/project/$projectId/usage'
    | '/project/$projectId/workflows'
    | '/project/$projectId'
    | '/project/$projectId/epics/$epicId'
    | '/project/$projectId/features/$featureId'
    | '/project/$projectId/sessions/$sessionId'
    | '/project/$projectId/settings/dns'
    | '/project/$projectId/settings/environment'
    | '/project/$projectId/settings/general'
    | '/project/$projectId/settings/github'
    | '/project/$projectId/artifacts'
    | '/project/$projectId/features'
    | '/project/$projectId/sessions'
    | '/project/$projectId/settings'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/login'
    | '/onboarding'
    | '/settings'
    | '/signup'
    | '/onboarding/done'
    | '/onboarding/invite'
    | '/onboarding/project'
    | '/onboarding/theme'
    | '/onboarding/welcome'
    | '/onboarding/workspace'
    | '/project/$projectId'
    | '/settings/members'
    | '/settings/profile'
    | '/settings/sandboxes'
    | '/settings/workspace'
    | '/onboarding/'
    | '/settings/'
    | '/project/$projectId/agents'
    | '/project/$projectId/artifacts'
    | '/project/$projectId/chains'
    | '/project/$projectId/config'
    | '/project/$projectId/epics'
    | '/project/$projectId/events'
    | '/project/$projectId/features'
    | '/project/$projectId/gates'
    | '/project/$projectId/insights'
    | '/project/$projectId/metrics'
    | '/project/$projectId/recovery'
    | '/project/$projectId/roadmap'
    | '/project/$projectId/roadmaps'
    | '/project/$projectId/sessions'
    | '/project/$projectId/settings'
    | '/project/$projectId/usage'
    | '/project/$projectId/workflows'
    | '/project/$projectId/'
    | '/project/$projectId/epics/$epicId'
    | '/project/$projectId/features/$featureId'
    | '/project/$projectId/sessions/$sessionId'
    | '/project/$projectId/settings/dns'
    | '/project/$projectId/settings/environment'
    | '/project/$projectId/settings/general'
    | '/project/$projectId/settings/github'
    | '/project/$projectId/artifacts/'
    | '/project/$projectId/features/'
    | '/project/$projectId/sessions/'
    | '/project/$projectId/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  SignupRoute: typeof SignupRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/settings/workspace': {
      id: '/settings/workspace'
      path: '/workspace'
      fullPath: '/settings/workspace'
      preLoaderRoute: typeof SettingsWorkspaceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/sandboxes': {
      id: '/settings/sandboxes'
      path: '/sandboxes'
      fullPath: '/settings/sandboxes'
      preLoaderRoute: typeof SettingsSandboxesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/members': {
      id: '/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof SettingsMembersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/workspace': {
      id: '/onboarding/workspace'
      path: '/workspace'
      fullPath: '/onboarding/workspace'
      preLoaderRoute: typeof OnboardingWorkspaceRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/theme': {
      id: '/onboarding/theme'
      path: '/theme'
      fullPath: '/onboarding/theme'
      preLoaderRoute: typeof OnboardingThemeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/project': {
      id: '/onboarding/project'
      path: '/project'
      fullPath: '/onboarding/project'
      preLoaderRoute: typeof OnboardingProjectRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/invite': {
      id: '/onboarding/invite'
      path: '/invite'
      fullPath: '/onboarding/invite'
      preLoaderRoute: typeof OnboardingInviteRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/done': {
      id: '/onboarding/done'
      path: '/done'
      fullPath: '/onboarding/done'
      preLoaderRoute: typeof OnboardingDoneRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/project/$projectId/': {
      id: '/project/$projectId/'
      path: '/'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof ProjectProjectIdIndexRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/workflows': {
      id: '/project/$projectId/workflows'
      path: '/workflows'
      fullPath: '/project/$projectId/workflows'
      preLoaderRoute: typeof ProjectProjectIdWorkflowsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/usage': {
      id: '/project/$projectId/usage'
      path: '/usage'
      fullPath: '/project/$projectId/usage'
      preLoaderRoute: typeof ProjectProjectIdUsageRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/settings': {
      id: '/project/$projectId/settings'
      path: '/settings'
      fullPath: '/project/$projectId/settings'
      preLoaderRoute: typeof ProjectProjectIdSettingsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/sessions': {
      id: '/project/$projectId/sessions'
      path: '/sessions'
      fullPath: '/project/$projectId/sessions'
      preLoaderRoute: typeof ProjectProjectIdSessionsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/roadmaps': {
      id: '/project/$projectId/roadmaps'
      path: '/roadmaps'
      fullPath: '/project/$projectId/roadmaps'
      preLoaderRoute: typeof ProjectProjectIdRoadmapsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/roadmap': {
      id: '/project/$projectId/roadmap'
      path: '/roadmap'
      fullPath: '/project/$projectId/roadmap'
      preLoaderRoute: typeof ProjectProjectIdRoadmapRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/recovery': {
      id: '/project/$projectId/recovery'
      path: '/recovery'
      fullPath: '/project/$projectId/recovery'
      preLoaderRoute: typeof ProjectProjectIdRecoveryRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/metrics': {
      id: '/project/$projectId/metrics'
      path: '/metrics'
      fullPath: '/project/$projectId/metrics'
      preLoaderRoute: typeof ProjectProjectIdMetricsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/insights': {
      id: '/project/$projectId/insights'
      path: '/insights'
      fullPath: '/project/$projectId/insights'
      preLoaderRoute: typeof ProjectProjectIdInsightsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/gates': {
      id: '/project/$projectId/gates'
      path: '/gates'
      fullPath: '/project/$projectId/gates'
      preLoaderRoute: typeof ProjectProjectIdGatesRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/features': {
      id: '/project/$projectId/features'
      path: '/features'
      fullPath: '/project/$projectId/features'
      preLoaderRoute: typeof ProjectProjectIdFeaturesRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/events': {
      id: '/project/$projectId/events'
      path: '/events'
      fullPath: '/project/$projectId/events'
      preLoaderRoute: typeof ProjectProjectIdEventsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/epics': {
      id: '/project/$projectId/epics'
      path: '/epics'
      fullPath: '/project/$projectId/epics'
      preLoaderRoute: typeof ProjectProjectIdEpicsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/config': {
      id: '/project/$projectId/config'
      path: '/config'
      fullPath: '/project/$projectId/config'
      preLoaderRoute: typeof ProjectProjectIdConfigRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/chains': {
      id: '/project/$projectId/chains'
      path: '/chains'
      fullPath: '/project/$projectId/chains'
      preLoaderRoute: typeof ProjectProjectIdChainsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/artifacts': {
      id: '/project/$projectId/artifacts'
      path: '/artifacts'
      fullPath: '/project/$projectId/artifacts'
      preLoaderRoute: typeof ProjectProjectIdArtifactsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/agents': {
      id: '/project/$projectId/agents'
      path: '/agents'
      fullPath: '/project/$projectId/agents'
      preLoaderRoute: typeof ProjectProjectIdAgentsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/settings/': {
      id: '/project/$projectId/settings/'
      path: '/'
      fullPath: '/project/$projectId/settings/'
      preLoaderRoute: typeof ProjectProjectIdSettingsIndexRouteImport
      parentRoute: typeof ProjectProjectIdSettingsRoute
    }
    '/project/$projectId/sessions/': {
      id: '/project/$projectId/sessions/'
      path: '/'
      fullPath: '/project/$projectId/sessions/'
      preLoaderRoute: typeof ProjectProjectIdSessionsIndexRouteImport
      parentRoute: typeof ProjectProjectIdSessionsRoute
    }
    '/project/$projectId/features/': {
      id: '/project/$projectId/features/'
      path: '/'
      fullPath: '/project/$projectId/features/'
      preLoaderRoute: typeof ProjectProjectIdFeaturesIndexRouteImport
      parentRoute: typeof ProjectProjectIdFeaturesRoute
    }
    '/project/$projectId/artifacts/': {
      id: '/project/$projectId/artifacts/'
      path: '/'
      fullPath: '/project/$projectId/artifacts/'
      preLoaderRoute: typeof ProjectProjectIdArtifactsIndexRouteImport
      parentRoute: typeof ProjectProjectIdArtifactsRoute
    }
    '/project/$projectId/settings/github': {
      id: '/project/$projectId/settings/github'
      path: '/github'
      fullPath: '/project/$projectId/settings/github'
      preLoaderRoute: typeof ProjectProjectIdSettingsGithubRouteImport
      parentRoute: typeof ProjectProjectIdSettingsRoute
    }
    '/project/$projectId/settings/general': {
      id: '/project/$projectId/settings/general'
      path: '/general'
      fullPath: '/project/$projectId/settings/general'
      preLoaderRoute: typeof ProjectProjectIdSettingsGeneralRouteImport
      parentRoute: typeof ProjectProjectIdSettingsRoute
    }
    '/project/$projectId/settings/environment': {
      id: '/project/$projectId/settings/environment'
      path: '/environment'
      fullPath: '/project/$projectId/settings/environment'
      preLoaderRoute: typeof ProjectProjectIdSettingsEnvironmentRouteImport
      parentRoute: typeof ProjectProjectIdSettingsRoute
    }
    '/project/$projectId/settings/dns': {
      id: '/project/$projectId/settings/dns'
      path: '/dns'
      fullPath: '/project/$projectId/settings/dns'
      preLoaderRoute: typeof ProjectProjectIdSettingsDnsRouteImport
      parentRoute: typeof ProjectProjectIdSettingsRoute
    }
    '/project/$projectId/sessions/$sessionId': {
      id: '/project/$projectId/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/project/$projectId/sessions/$sessionId'
      preLoaderRoute: typeof ProjectProjectIdSessionsSessionIdRouteImport
      parentRoute: typeof ProjectProjectIdSessionsRoute
    }
    '/project/$projectId/features/$featureId': {
      id: '/project/$projectId/features/$featureId'
      path: '/$featureId'
      fullPath: '/project/$projectId/features/$featureId'
      preLoaderRoute: typeof ProjectProjectIdFeaturesFeatureIdRouteImport
      parentRoute: typeof ProjectProjectIdFeaturesRoute
    }
    '/project/$projectId/epics/$epicId': {
      id: '/project/$projectId/epics/$epicId'
      path: '/$epicId'
      fullPath: '/project/$projectId/epics/$epicId'
      preLoaderRoute: typeof ProjectProjectIdEpicsEpicIdRouteImport
      parentRoute: typeof ProjectProjectIdEpicsRoute
    }
  }
}

interface OnboardingRouteChildren {
  OnboardingDoneRoute: typeof OnboardingDoneRoute
  OnboardingInviteRoute: typeof OnboardingInviteRoute
  OnboardingProjectRoute: typeof OnboardingProjectRoute
  OnboardingThemeRoute: typeof OnboardingThemeRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
  OnboardingWorkspaceRoute: typeof OnboardingWorkspaceRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingDoneRoute: OnboardingDoneRoute,
  OnboardingInviteRoute: OnboardingInviteRoute,
  OnboardingProjectRoute: OnboardingProjectRoute,
  OnboardingThemeRoute: OnboardingThemeRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
  OnboardingWorkspaceRoute: OnboardingWorkspaceRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface SettingsRouteChildren {
  SettingsMembersRoute: typeof SettingsMembersRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSandboxesRoute: typeof SettingsSandboxesRoute
  SettingsWorkspaceRoute: typeof SettingsWorkspaceRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsMembersRoute: SettingsMembersRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSandboxesRoute: SettingsSandboxesRoute,
  SettingsWorkspaceRoute: SettingsWorkspaceRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ProjectProjectIdArtifactsRouteChildren {
  ProjectProjectIdArtifactsIndexRoute: typeof ProjectProjectIdArtifactsIndexRoute
}

const ProjectProjectIdArtifactsRouteChildren: ProjectProjectIdArtifactsRouteChildren =
  {
    ProjectProjectIdArtifactsIndexRoute: ProjectProjectIdArtifactsIndexRoute,
  }

const ProjectProjectIdArtifactsRouteWithChildren =
  ProjectProjectIdArtifactsRoute._addFileChildren(
    ProjectProjectIdArtifactsRouteChildren,
  )

interface ProjectProjectIdEpicsRouteChildren {
  ProjectProjectIdEpicsEpicIdRoute: typeof ProjectProjectIdEpicsEpicIdRoute
}

const ProjectProjectIdEpicsRouteChildren: ProjectProjectIdEpicsRouteChildren = {
  ProjectProjectIdEpicsEpicIdRoute: ProjectProjectIdEpicsEpicIdRoute,
}

const ProjectProjectIdEpicsRouteWithChildren =
  ProjectProjectIdEpicsRoute._addFileChildren(
    ProjectProjectIdEpicsRouteChildren,
  )

interface ProjectProjectIdFeaturesRouteChildren {
  ProjectProjectIdFeaturesFeatureIdRoute: typeof ProjectProjectIdFeaturesFeatureIdRoute
  ProjectProjectIdFeaturesIndexRoute: typeof ProjectProjectIdFeaturesIndexRoute
}

const ProjectProjectIdFeaturesRouteChildren: ProjectProjectIdFeaturesRouteChildren =
  {
    ProjectProjectIdFeaturesFeatureIdRoute:
      ProjectProjectIdFeaturesFeatureIdRoute,
    ProjectProjectIdFeaturesIndexRoute: ProjectProjectIdFeaturesIndexRoute,
  }

const ProjectProjectIdFeaturesRouteWithChildren =
  ProjectProjectIdFeaturesRoute._addFileChildren(
    ProjectProjectIdFeaturesRouteChildren,
  )

interface ProjectProjectIdSessionsRouteChildren {
  ProjectProjectIdSessionsSessionIdRoute: typeof ProjectProjectIdSessionsSessionIdRoute
  ProjectProjectIdSessionsIndexRoute: typeof ProjectProjectIdSessionsIndexRoute
}

const ProjectProjectIdSessionsRouteChildren: ProjectProjectIdSessionsRouteChildren =
  {
    ProjectProjectIdSessionsSessionIdRoute:
      ProjectProjectIdSessionsSessionIdRoute,
    ProjectProjectIdSessionsIndexRoute: ProjectProjectIdSessionsIndexRoute,
  }

const ProjectProjectIdSessionsRouteWithChildren =
  ProjectProjectIdSessionsRoute._addFileChildren(
    ProjectProjectIdSessionsRouteChildren,
  )

interface ProjectProjectIdSettingsRouteChildren {
  ProjectProjectIdSettingsDnsRoute: typeof ProjectProjectIdSettingsDnsRoute
  ProjectProjectIdSettingsEnvironmentRoute: typeof ProjectProjectIdSettingsEnvironmentRoute
  ProjectProjectIdSettingsGeneralRoute: typeof ProjectProjectIdSettingsGeneralRoute
  ProjectProjectIdSettingsGithubRoute: typeof ProjectProjectIdSettingsGithubRoute
  ProjectProjectIdSettingsIndexRoute: typeof ProjectProjectIdSettingsIndexRoute
}

const ProjectProjectIdSettingsRouteChildren: ProjectProjectIdSettingsRouteChildren =
  {
    ProjectProjectIdSettingsDnsRoute: ProjectProjectIdSettingsDnsRoute,
    ProjectProjectIdSettingsEnvironmentRoute:
      ProjectProjectIdSettingsEnvironmentRoute,
    ProjectProjectIdSettingsGeneralRoute: ProjectProjectIdSettingsGeneralRoute,
    ProjectProjectIdSettingsGithubRoute: ProjectProjectIdSettingsGithubRoute,
    ProjectProjectIdSettingsIndexRoute: ProjectProjectIdSettingsIndexRoute,
  }

const ProjectProjectIdSettingsRouteWithChildren =
  ProjectProjectIdSettingsRoute._addFileChildren(
    ProjectProjectIdSettingsRouteChildren,
  )

interface ProjectProjectIdRouteChildren {
  ProjectProjectIdAgentsRoute: typeof ProjectProjectIdAgentsRoute
  ProjectProjectIdArtifactsRoute: typeof ProjectProjectIdArtifactsRouteWithChildren
  ProjectProjectIdChainsRoute: typeof ProjectProjectIdChainsRoute
  ProjectProjectIdConfigRoute: typeof ProjectProjectIdConfigRoute
  ProjectProjectIdEpicsRoute: typeof ProjectProjectIdEpicsRouteWithChildren
  ProjectProjectIdEventsRoute: typeof ProjectProjectIdEventsRoute
  ProjectProjectIdFeaturesRoute: typeof ProjectProjectIdFeaturesRouteWithChildren
  ProjectProjectIdGatesRoute: typeof ProjectProjectIdGatesRoute
  ProjectProjectIdInsightsRoute: typeof ProjectProjectIdInsightsRoute
  ProjectProjectIdMetricsRoute: typeof ProjectProjectIdMetricsRoute
  ProjectProjectIdRecoveryRoute: typeof ProjectProjectIdRecoveryRoute
  ProjectProjectIdRoadmapRoute: typeof ProjectProjectIdRoadmapRoute
  ProjectProjectIdRoadmapsRoute: typeof ProjectProjectIdRoadmapsRoute
  ProjectProjectIdSessionsRoute: typeof ProjectProjectIdSessionsRouteWithChildren
  ProjectProjectIdSettingsRoute: typeof ProjectProjectIdSettingsRouteWithChildren
  ProjectProjectIdUsageRoute: typeof ProjectProjectIdUsageRoute
  ProjectProjectIdWorkflowsRoute: typeof ProjectProjectIdWorkflowsRoute
  ProjectProjectIdIndexRoute: typeof ProjectProjectIdIndexRoute
}

const ProjectProjectIdRouteChildren: ProjectProjectIdRouteChildren = {
  ProjectProjectIdAgentsRoute: ProjectProjectIdAgentsRoute,
  ProjectProjectIdArtifactsRoute: ProjectProjectIdArtifactsRouteWithChildren,
  ProjectProjectIdChainsRoute: ProjectProjectIdChainsRoute,
  ProjectProjectIdConfigRoute: ProjectProjectIdConfigRoute,
  ProjectProjectIdEpicsRoute: ProjectProjectIdEpicsRouteWithChildren,
  ProjectProjectIdEventsRoute: ProjectProjectIdEventsRoute,
  ProjectProjectIdFeaturesRoute: ProjectProjectIdFeaturesRouteWithChildren,
  ProjectProjectIdGatesRoute: ProjectProjectIdGatesRoute,
  ProjectProjectIdInsightsRoute: ProjectProjectIdInsightsRoute,
  ProjectProjectIdMetricsRoute: ProjectProjectIdMetricsRoute,
  ProjectProjectIdRecoveryRoute: ProjectProjectIdRecoveryRoute,
  ProjectProjectIdRoadmapRoute: ProjectProjectIdRoadmapRoute,
  ProjectProjectIdRoadmapsRoute: ProjectProjectIdRoadmapsRoute,
  ProjectProjectIdSessionsRoute: ProjectProjectIdSessionsRouteWithChildren,
  ProjectProjectIdSettingsRoute: ProjectProjectIdSettingsRouteWithChildren,
  ProjectProjectIdUsageRoute: ProjectProjectIdUsageRoute,
  ProjectProjectIdWorkflowsRoute: ProjectProjectIdWorkflowsRoute,
  ProjectProjectIdIndexRoute: ProjectProjectIdIndexRoute,
}

const ProjectProjectIdRouteWithChildren =
  ProjectProjectIdRoute._addFileChildren(ProjectProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  SignupRoute: SignupRoute,
  ProjectProjectIdRoute: ProjectProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
